spring:
  application:
    name: fakecommerce
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration




